#%RAML 1.0
title: "Weather API"
baseUri: http://localhost:81/weatherAPI/v1.0
version: 1.0
types:
  Name:
    type: string
    required: true
    pattern: "^[0-9A-Za-z -]+$"
    maxLength: 50
/countries:
  description: Get all cities.,
  get:
    responses :
      200:
        body:
          application/json:
              example: |
                {
                  [
                    {
                      "countryName" : "Australia",
                      "cityName" : "Moorabin Airport"
                    },
                    {
                      "countryName" : "Canada",
                      "cityName" : "Hamilton Airport"
                    },
                    {
                      "countryName" : "Canada",
                      "cityName" : "Windsor, Ont."
                    }
                  ],
                  "success": true,
                  "status": 200
                }
      404:
        body:
          application/json:
            example: |
             { "message": "Resource not found" }
      405:
        body:
          application/json:
            example: |
             { "message": "Method not allowed" }
      415:
        body:
          application/json:
            example: |
             { "message": "Unsupported media type" }
      406:
        body:
          application/json:
            example: |
             { "message": "Not acceptable" }
      400:
        body:
          application/json:
            example: |
             { "message": "Bad request" }
      500:
        body:
          application/json:
            example: |
             { "message": "Unexpected error" }
  /{countryName}:
    description: Gets cities by country.
    uriParameters:
     countryName:
       description: Country Name
       type: Name
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  [
                    {
                      "countryName" : "Canada",
                      "cityName" : "Hudson Bay, Sask."
                    },
                    {
                      "countryName" : "Canada",
                      "cityName" : "Hamilton Airport"
                    },
                    {
                      "countryName" : "Canada",
                      "cityName" : "Windsor, Ont."
                    }
                  ],
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
               { "message": "Resource not found" }
        405:
          body:
            application/json:
              example: |
               { "message": "Method not allowed" }
        415:
          body:
            application/json:
              example: |
               { "message": "Unsupported media type" }
        406:
          body:
            application/json:
              example: |
               { "message": "Not acceptable" }
        400:
          body:
            application/json:
              example: |
               { "message": "Bad request" }
        500:
          body:
            application/json:
              example: |
               { "message": "Unexpected error" }
    /cities:
      /{cityName}:
        description: Get weather report by country and city.
        uriParameters:
          cityName:
            description: City Name
            type: Name
        get:
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      {
                        "location": "Melbourne",
                        "time": "11 AM",
                        "wind": "15 km per hour",
                        "visibility": "19 km",
                        "skyConditions": "sunny",
                        "temperature": "18",
                        "dewPoint": "2 C",
                        "relativeHumidity": "35",
                        "status": "Normal"
                      },
                      "success": true,
                      "status": 200
                    }
            404:
              body:
                application/json:
                  example: |
                   { "message": "Resource not found" }
            405:
              body:
                application/json:
                  example: |
                   { "message": "Method not allowed" }
            415:
              body:
                application/json:
                  example: |
                   { "message": "Unsupported media type" }
            406:
              body:
                application/json:
                  example: |
                   { "message": "Not acceptable" }
            400:
              body:
                application/json:
                  example: |
                   { "message": "Bad request" }
            500:
              body:
                application/json:
                  example: |
                   { "message": "Unexpected error" }